# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1.2
loader_version=0.19.5
# Mod Properties
mod_version=1.0
maven_group=org.dreamscape_lab
archives_base_name=EMF_Compat_Basic_Weapons
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.155.3+26.1.2
emf_compat_core_version=wu5LmVV7
emf_version=x608KQlq
etf_version=LnTUlq1r
basic_weapons_version=BONRhyAx
khazoda_core_version=ca8YAVE6
punchy_version=bq92Ivky
